### ISSUE TITLE
dank storabge upgread recipe issues 

### ISSUE THREAD

**Issue by akasia** [MindBrain27/Sky-Greg#23]
dank storange 5 to 6 recipe difrent crafte using crying obsidian if uprade using 5 to 6 with dock just using obsidian skip mv tier (crying obsidian)
![2024-01-07_11 56 08](https://github.com/MindBrain27/Sky-Greg/assets/14824981/713e77a6-65ee-4f0a-afa2-9f1df3929f83)
![2024-01-07_11 56 12](https://github.com/MindBrain27/Sky-Greg/assets/14824981/b92b1908-80ca-4307-ab87-bfb7b4bad9a5)

**Comment by MindBrain27** [comment]
Good call, I am going to change the first one to have the Crying Obsidian and Amethyst because changing upgrade recipes is better than changing Dank recipes (if not done correctly they won't keep their contents on upgrading).

Will be addressed in next update, which should be soon because there was a decent GT update yesterday I want to get out.

**Comment by akasia** [comment]
nice~~

**Comment by MindBrain27** [comment]
Done in new update.
