### ISSUE TITLE
need some help here EBF with kental recpie

### ISSUE THREAD

**Issue by akasia** [MindBrain27/Sky-Greg#30]
i just try set up kental ingot but EBF seem like can't gen enough power 4 mv steam turbine 2 mv energy hatch using 2x cupronickel cable   
still strgule with energy ?what has i setup wrong?
![2024-01-10_08 00 52](https://github.com/MindBrain27/Sky-Greg/assets/14824981/9dbb3630-0c78-4027-bdca-bb14c5be9310)
![2024-01-10_08 03 08](https://github.com/MindBrain27/Sky-Greg/assets/14824981/eb3c7115-de47-48a8-86de-0939daa7282c)
![2024-01-10_08 04 11](https://github.com/MindBrain27/Sky-Greg/assets/14824981/b5311d3d-537c-4b51-8cee-bbb42f91098d)
![2024-01-10_08 04 17](https://github.com/MindBrain27/Sky-Greg/assets/14824981/d69d91f6-5c41-4278-a59e-6433e8163783)
![2024-01-10_08 04 23](https://github.com/MindBrain27/Sky-Greg/assets/14824981/3b05e50a-4761-45b0-94f6-0eeb935846a5)

keep turn on and off
![2024-01-10_08 19 39](https://github.com/MindBrain27/Sky-Greg/assets/14824981/ab2b5ac2-83bc-4451-9598-2e80cd99949d)
![2024-01-10_08 19 38_3](https://github.com/MindBrain27/Sky-Greg/assets/14824981/89fc194c-c71c-4e9b-a34f-8576d367582a)

zzzz  need 5 steam turbine to let it run?  
![2024-01-10_08 15 16](https://github.com/MindBrain27/Sky-Greg/assets/14824981/310f3519-54c9-4323-9ccd-d4bac16aa938)
![2024-01-10_08 15 16](https://github.com/MindBrain27/Sky-Greg/assets/14824981/139add7c-641c-4aba-be79-7e8f0a0bdea5)

**Comment by MindBrain27** [comment]
Are your Steam Turbines getting enough Steam? I need to use 2 Card Overclockers for 1 MV Steam Turbine usually, and I turn the amount transferred to max (4000) and the tick rate to the lowest (10). Since your setup uses 1 Laser Node for 2 Turbines you may need 4 Card Overclockers in each Laser Node. Other than that your setup looks like it should work, I jut use 4x Cables is the only difference it looks like but you don't need 4x.

![Overclockers](https://github.com/MindBrain27/Sky-Greg/assets/74363414/9e442ba6-a6f6-4e09-b0b1-f8ee4c7062d5)

This is what my Extract Fluid Card settings look like to keep up with the Steam requirements.

**Comment by akasia** [comment]
ahh i dump 1 of my turbine didt turn at right place my bad sorry
