### ISSUE TITLE
GregTech pumps stop when entering the world.

### ISSUE THREAD

**Issue by DEMAXGAMER195** [MindBrain27/Sky-Greg#32]
I have noticed that the pump covers by GregTech stop working when I reload the world. Specifically when importing steam from tanks by DimStorage into my steam turbines, they won't import until I break and replace the tank. I don't know if it is a problem with GT or DimStorage. I may have to change to ender tanks, but if the pumps are broken, then I don't think there is another way to transfer huge amounts of liquids like 1k mb/t.

**Comment by DEMAXGAMER195** [comment]
Ok just tested it. It looks like the pump covers are the ones breaking. Then I have to find some other way to transport steam.

**Comment by MindBrain27** [comment]
I have an issue open on the GT github currently for this, I'm really hoping this is addressed sooner than later on their end. My work around for now has been using Ender Tanks/Dimensional Tanks and LaserIO. LaserIO can transfer up to 8000 mb/t with 4 Card Overclockers.

It seems GT has an issue on loading the world where some auto import/export features stop. Before I added other logistic methods my boilers were exploding quite often due to not getting Water.

This is definitely a problem on GregTech's end as having anything trigger an update seems to work, like LaserIO or an EnderIO Conduit, however with EnderIO not having upgrades available, that would just leave LaserIO for now for fast transfer rates.

I did notice that Dimensional Tanks set to auto export mode are also good enough to trigger updates on world entry.

The thing that suffers the most seem to be Electric Pumps and Input Busses/Hatches (output seems to be fine).

I have also added Modular Routers for the next update which may help some cases.

This has been quite frustrating but I'm hoping it's fixed soon, GT has been doing pretty steady updates so fingers crossed it's one of the next few.

**Comment by MindBrain27** [comment]
I'm open to adding more logistics choices as well, anything but Pipez or Pretty Pipes for the most part.

**Comment by MindBrain27** [comment]
I have my Large Boilers auto exporting Steam into Dimensional Tanks and I usually put a Dimensional Tank on a machine that requires Steam and set it to auto export mode. The auto export speed will hold up to any LV Turbine, an MV Turbine I use a LaserIO Node with 2 Card Overclockers to extract Steam from the Dimensional Tank and send it to the MV Turbine. It's kind of costly on Steel Ingots but it works quite well.

**Comment by MindBrain27** [comment]
Another option for Steam transport is also AE2 with ME Interfaces and Import/Export Busses, AE2 can be one of the fastest methods.

**Comment by akasia** [comment]
there is more than pump tranfer olso machines when load in the world some time olso will stop working if input fill with ingredian olso

**Comment by MindBrain27** [comment]
https://github.com/GregTechCEu/GregTech-Modern/issues/643#event-11508044551

This issue was just closed So I'm hoping the next GT update addresses this.

**Comment by MindBrain27** [comment]
I believe this has been fixed with the newest GT update, pack update today or tomorrow with quite a bit.

**Comment by MindBrain27** [comment]
I believe this has been fixed with newest GT update. "fixed distinct buses not working after reloading the world", my testing so far seems to be working, closing this for now. Feel free to re open an issue if something comes back up.
