### ISSUE TITLE
Shield Bug

### ISSUE THREAD

**Issue by adk95** [MindBrain27/Sky-Greg#71]
When having shield in off hand cannot access storage drawers, cannot use wrench to rotate among other possible things

**Comment by adk95** [comment]
Also when using the universal wireless terminal , having a pattern encoding terminal does not pull recipes that are in machines for creating pattern 

![image](https://github.com/MindBrain27/Sky-Greg/assets/50649069/3e3520ab-ce0b-454c-bda8-293ee22a0a50)

![image](https://github.com/MindBrain27/Sky-Greg/assets/50649069/0812a3b9-e157-453b-bbe0-23664678c5a8)

**Comment by MindBrain27** [comment]
The shield bug is a strange one I'll have to test that, but the ae2 wireless terminal one is known and annoying, it works fine from the main terminal but not for processing patterns in the wireless terminals. It could be EMI but I believe it still happens with JEI as well.

**Comment by MindBrain27** [comment]
With the shield I seem to be able to do most things but I can't do anything that requires sneaking and right clicking as that is vanilla mechanics to activate your offhand instead of your main hand. I can set output sides on machines using a Wrench but I can't rotate machines, which is as intended. There are some settings involving the shield/off hand in the Client Tweaks mod configs if you wanted to change anything back to normal behavior.

**Comment by MindBrain27** [comment]
I spoke too soon, recent GT update fixed the processing patterns with the wireless terminals.
